---
- name: Detect and Execute RHEL 6 OS-specific tasks
  hosts: "{{ host_list }}"
  gather_facts: yes
  vars:
    domain_name: "wikilab.asia"
    username: "{{ username }}"
    password: "{{ pass }}"

  tasks:

    - name: Check if running on RHEL 6
      fail:
        msg: "This playbook only runs on RHEL 6 servers."
      when: ansible_distribution_major_version | int != 6
      tags: always

    - name: Gather OS version and distribution facts
      debug:
        var: ansible_distribution_version
      register: os_version

    - name: Extract OS major version from facts
      set_fact:
        ansible_distribution_major_version: "{{ ansible_distribution_version.split('.')[0] }}"

    - name: Print the OS major version
      debug:
        var: ansible_distribution_major_version

    #Prechecks to Join Domain
    - name: Check if user {{ username }} exists in RHEL6
      shell: getent passwd {{ username }}
      register: check_user
      changed_when: False
      ignore_errors: True

    - name: Print failure message if AD user check failed
      debug:
        msg: "Check failed: AD user '{{ username }}' does not exist on {{ ansible_facts['fqdn'] }}"
      when: check_user.rc != 0

    - name: Check if LDAP port is in use
      shell: lsof -i:636
      register: check_ldap
      changed_when: False
      ignore_errors: True

    - name: Print failure message if LDAP port check failed
      debug:
        msg: "Check failed: LDAP port 636 is not listening on {{ ansible_facts['fqdn'] }}"
      when: check_ldap.rc != 0

    - name: Print success message if RHEL 6 server joined domain
      debug:
        msg: "RHEL 6 server joined domain"
      when: check_user.rc == 0 and check_ldap.rc == 0

    - name: Print failure message if RHEL 6 server Not joined domain
      debug:
        msg: "{{ ansible_facts['fqdn'] }} server need to joined domain"
      when: check_user.rc != 0 or check_ldap.rc != 0

    - name: Exit the playbook if RHEL 789 server joined domain
      fail:
        msg: "This Server Already Joined Domain."
      when: check_user.rc == 0 and check_ldap.rc == 0
      tags: always

    #    - name: Exit the playbook if RHEL 6 server joined domain
    #      meta: end_play
    #      when: check_user.rc == 0 and check_ldap.rc == 0

    #Install packages and Join Domain
    - name: Installing packages in RHEL 6 server
      package:
        name: "{{ item }}"
        state: latest
      with_items:
        - adcli
        - sssd
        - authconfig
        - oddjob
        - oddjob-mkhomedir
        - lsof

    - name: RHEL 6 server join domain
      shell: echo -n "{{ password }}" | adcli join {{ domain_name }} -U {{ username }} -v --stdin-password
      register: join_domain
      ignore_errors: yes
      no_log: true
          
    - name: Print server join domain error message if any
      debug:
        var: join_domain.stderr_lines
      when: join_domain.rc != 0

    - name: Update nsswitch.conf configuration file
      replace:
        path: /etc/nsswitch.conf
        regexp: "{{ item.regexp }}"
        replace: "{{ item.replace }}"
        backup: true
      with_items:
        - { regexp: '^passwd:.*', replace: 'passwd: files sss' }
        - { regexp: '^group:.*', replace: 'group: files sss' }

    - name: Enable SSSD Authentication in PAM
      command: authconfig --enablesssdauth --enablesssd --enablemkhomedir --updateall
      ignore_errors: yes
 
    - name: Modify SSSD Configuration in RHEL6
      copy:
        src: sssd.conf_rhel6_v2
        dest: /etc/sssd/sssd.conf
        mode: "0600"

    - name: Modify ldap Configuration in RHEL6
      copy:
        src: ldap.conf_rhel6
        dest: /etc/openldap/ldap.conf
        mode: "0644"

    - name: Copy LDAP CERT
      copy:
        src: LDAPS_CERT6.cer
        dest: /etc/openldap/certs
        mode: "0655"

    - name: CERT Rehash in RHLE 6
      shell: cacertdir_rehash /etc/openldap/certs
      when: ansible_distribution_major_version|int == 6

    - name: Restart sssd
      service:
        name: sssd
        state: restarted

#Post validation of Join Domain
    - name: Copy both sshpass RPM files to /tmp
      copy:
        src: sshpass-1.06-1.el6.x86_64.rpm
        dest: /tmp

    - name: Install sshpass package
      shell: yum install /tmp/sshpass-1.06-1.el6.x86_64.rpm -y
      ignore_errors: True

    - name: Check ID for AD user
      shell: id {{username}}
      register: check_user
      changed_when: False
      ignore_errors: True

    - name: Print result ID for AD user
      debug:
        msg: >-
          {% if check_user.rc != 0 %}
          Check failed: AD user '{{ username }}' does not exist on {{ ansible_facts['fqdn'] }}
          {% else %}
          Check Pass: AD user '{{ username }}' exist on {{ ansible_facts['fqdn'] }}
          {% endif %}

    - name: Check if LDAP port is in use
      shell: lsof -i:636
      register: check_ldap
      changed_when: False
      ignore_errors: True

    - name: Print result LDAP port is in use
      debug:
        msg: >-
          {% if check_ldap.rc != 0 %}
          Check failed: LDAP port 636 is not listening on {{ ansible_facts['fqdn'] }}
          {% else %}
          Check Pass: LDAP port 636 is listening on {{ ansible_facts['fqdn'] }}
          {% endif %}

    - name: login AD user Account
      shell: sshpass -p "{{password}}" ssh {{username}}@localhost pwd
      register: ssh

    - name: Print result LDAP port is in use
      debug:
        msg: >-
          {% if ssh.rc != 0 %}
          Check failed: Unable to login as AD user '{{ username }}' on {{ ansible_facts['fqdn'] }}
          {% else %}
          Check Pass: Login as AD user '{{ username }}' on {{ ansible_facts['fqdn'] }}"
          {% endif %}

    - name: Print result of all checks
      debug:
        msg: >-
          {% if check_user.rc == 0 and check_ldap.rc == 0 and ssh.rc == 0 %}
          Successfully joined server {{ ansible_facts['fqdn'] }} to the domain
          {% else %}
          Failed joined server {{ ansible_facts['fqdn'] }} to the domain, Check manually or rerun playbook.
          {% endif %}
